name: build-gleam

on:
  pull_request:
    paths:
      - "src/server/client/**"
      - ".github/workflows/build-gleam.yml"

env:
  GLEAM_VERSION: '1.10.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure dev flag is set to False
        run: |
          if grep -q "const dev = True" src/server/client/src/effects.gleam; then
            echo "dev flag is set to True"
            false
          fi
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1"
          gleam-version: ${{ env.GLEAM_VERSION }}
          rebar3-version: "3"
      - name: Compile gleam to js
        run: |
          cd src/server/client
          gleam run -m lustre/dev build app
      - name: Ensure compiled files haven't changed
        run: |
          if git --no-pager diff --name-only | grep -q "priv/static"; then
            echo "compiled files have changed; compile them again"
            git --no-pager diff --name-only
            false
          fi
