name: preview-public-version

on:
  pull_request:
    paths:
      - "src/server/client/**"
      - ".github/workflows/preview-public-version.yml"

env:
  GLEAM_VERSION: '1.10.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy-on-vercel
        with:
          environment: preview
          gleam_version: ${{ env.GLEAM_VERSION }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
